version: '3.1'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.kind == rabbit
    networks:
      - int-net
  handler:
    image: 80.247.66.205:5000/wkidiff/handler 
    depends_on:
      - rabbit
    deploy:
      placement:
        constraints:
          - engine.labels.kind == backend
      replicas: 1
      resources:
          limits:
              cpus: '0.25'
              memory: 100M
          reservations:
              cpus: '0.25'
              memory: 20M
    networks:
      - int-net
  worker:
    image: 80.247.66.205:5000/wkidiff/worker
    secrets:
      - aws-credential
    depends_on:
      - rabbit
    environment:
      - "AWS_CREDENTIAL_FILENAME=/var/run/secrets/aws-credential"

    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.kind == backend
      resources:
          limits:
              cpus: '1'
              memory: 300M
          reservations:
              cpus: '1'
              memory: 100M
    networks:
      - int-net
networks:
  int-net:
    external: true

secrets:
  aws-credential:
    external: true
