version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
    deploy:
      replicas: 1
    networks:
      - micro-net
    #micro:
      #image: node
      #networks:
        #- micro-net
      #deploy:
        #mode: replicated
        #replicas: 1
        #labels: [app=http]
        #resources:
            ## Hard limit - Docker does not allow to allocate more
            #limits:
                #cpus: '0.25'
                #memory: 512M
            ## Soft limit - Docker makes best effort to return to it
            #reservations:
                #cpus: '0.25'
                #memory: 256M
        ## service restart policy
        #restart_policy:
            #condition: on-failure
            #delay: 5s
            #max_attempts: 3
            #window: 120s

networks:
    micro-net:
