version: '3.1'
services:
  orbiter:
    image: gianarb/orbiter
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "DOCKER_HOST=unix:///var/run/docker.sock"
    command: daemon -debug
    depends_on:
      - worker
    networks:
      - int-net
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.kind == rabbit
    networks:
      - int-net
  handler:
    image: gianarb/wikidiff-handler
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      resources:
          limits:
              cpus: '0.25'
              memory: 100M
          reservations:
              cpus: '0.25'
              memory: 20M
    networks:
      - int-net
  worker:
    image: gianarb/wikidiff-worker
    secrets:
      - aws-credential
    depends_on:
      - rabbit
    environment:
      - "AWS_CREDENTIAL_FILENAME=/var/run/secrets/aws-credential"
    networks:
      - int-net
    deploy:
      replicas: 1
      labels:
        orbiter: "true"
        orbiter_up: 3
        orbiter_down: 2
      resources:
          limits:
              cpus: '1'
              memory: 300M
          reservations:
              cpus: '1'
              memory: 100M
networks:
  int-net:
    external: true

secrets:
  aws-credential:
    external: true
