version: "3.2"
services:
  influxdb:
      image: influxdb:1.2.0
      networks:
        - int-net
      #environment:
        #- INFLUXDB_HTTP_BIND_ADDRESS="127.0.0.1:8086"
      ports:
        - "8086:8086"
  #kapacitor:
      #image: kapacitor:1.2.0
      #secrets:
        #- tick_kapacitor-configuration
      #networks:
        #- int-net
      #ports:
        #- "9092:9092"
      #deploy:
        #placement:
          #constraints: [node.role == rabbit]
        #replicas: 1
  chronograf:
      image: quay.io/influxdb/chronograf
      networks:
        - int-net
      ports:
        - "8888:8888"
      ports:
        - target: 8888
          published: 8888
          protocol: tcp
          #mode: ingress
networks:
  int-net:

secrets:
  tick_kapacitor-configuration:
    external: true
